services:
  - type: web
    name: frontend-angkutan
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://backend-angkutan.onrender.com/api/web
      - key: REACT_APP_BACKEND_URL
        value: https://backend-angkutan.onrender.com
